# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LxSocketManage2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'CocoaAsyncSocket', '~> 7.6.3'
  # Pods for LxSocketManage2

  target 'LxSocketManage2Tests' do
    inherit! :search_paths

    # Pods for testing
  end

  target 'LxSocketManage2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
